//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knowledgeBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.IsRefer = false;
            this.PeopleLike = new HashSet<Person>();
            this.PeopleDislike = new HashSet<Person>();
            this.ChildComments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> LikeNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ParentCommentId { get; set; }
        public int QuestionId { get; set; }
        public bool IsRefer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> PeopleLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> PeopleDislike { get; set; }
        public virtual Person Person { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> ChildComments { get; set; }
        public virtual Comment ParentComment { get; set; }
    }
}
