//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knowledgeBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.LikeNumber = 0;
            this.Summary = "";
            this.State = "Open";
            this.IsPrivate = false;
            this.Comments = new HashSet<Comment>();
            this.ReferPeople = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int LikeNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Summary { get; set; }
        public string State { get; set; }
        public bool IsPrivate { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> ReferPeople { get; set; }
        public virtual Person Supportor { get; set; }
        public virtual Product Product { get; set; }
    }
}
